repos:
  - repo: "https://github.com/pre-commit/mirrors-isort"
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: "https://github.com/codespell-project/codespell"
    rev: v2.2.2
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: "https://github.com/psf/black"
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - "--safe"
          - "--quiet"
  - repo: "https://github.com/pycqa/flake8"
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.6.0
          - pydocstyle==6.1.1
        files: ^app.py|(script)\/.+\.py$

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-yaml
      args: [--unsafe]
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-docstring-first
    - id: fix-byte-order-marker
    - id: check-shebang-scripts-are-executable
    - id: check-toml
  - repo: local
    hooks:
      - id: check_shellcheck
        name: check_shellcheck
        entry: script/pre_commit_shellcheck.sh
        language: script
        exclude_types: [json, sql, toml, yaml]
        files: ^(script|iac)/.+sh$
      - id: pylint
        name: pylint
        entry: script/run_in_env.sh pylint -j 0
        language: script
        types: [python]
