[project]
name        = "trykle-web"
version     = "2023.12.1"
description = "briglx/trykle-web"
readme      = "README.md"

[tool.codespell]
skip = '.*,*.map,static/js/bootstrap.*.js,static/js/bootstrap.bundle.js,static/js/bootstrap.bundle.*.js'
