name: Linter for Azure Web App - trykle

on:
  push:
    branches:
      - main

jobs:
  prepare-base:
    name: Prepare base dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Check out code from GitHub
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Create Python virtual environment
      run: |
          python -m venv venv
          . venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt

  lint-black:
    name: Check black
    runs-on: ubuntu-latest
    needs: prepare-base
    steps:
    - name: Check out code from GitHub
    - uses: actions/checkout@master
    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Run black
      run: |
        black .