name: CI

on:
  push:
    branches:
      - main

jobs:

  lint-black:
    name: Check black
    runs-on: ubuntu-latest
    needs: prepare-base
    steps:
    
    - name: Check out code from GitHub
      uses: actions/checkout@master
    
    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    
    - name: Create Python virtual environment
      run: |
          python -m venv venv
          . venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
    
    - name: Run black
      run: |
        black .