name: CI

on:
  push:
    branches:
      - main

jobs:

  lint-black:
    name: Check black
    runs-on: ubuntu-latest

    steps:

    - name: Check out code from GitHub
      uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

    - name: Run black
      run: |
        black .
